# Generated by Django 5.0.3 on 2024-03-16 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("group_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(default="", max_length=100)),
                ("body", models.TextField(default="")),
                ("place", models.CharField(max_length=20)),
                ("detail_place", models.CharField(max_length=100)),
                (
                    "group_image",
                    models.ImageField(blank=True, upload_to="groups/%Y/%m/%d"),
                ),
                ("link", models.URLField(verbose_name="Site URL")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closing_time", models.DateTimeField()),
                ("max_people", models.IntegerField()),
                ("group_status", models.BooleanField(default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "group",
            },
        ),
        migrations.CreateModel(
            name="Participate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_owner", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="groups.group"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "participate",
            },
        ),
    ]
